/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness check — does not touch the database.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness check — confirms the database connection works.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/registration-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Registration Status
         * @description Only expose registration while the single-teacher database has no account.
         */
        get: operations["registration_status_api_auth_registration_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description One-time bootstrap registration; permanently closes once an account exists.
         */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Courses */
        get: operations["list_courses_api_courses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/standards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Standards */
        get: operations["list_standards_api_standards_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/standards/{standard_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Standard Detail */
        get: operations["get_standard_detail_api_standards__standard_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Topics */
        get: operations["list_topics_api_topics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bundles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Bundles */
        get: operations["list_bundles_api_bundles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_api_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/families": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Families */
        get: operations["list_families_api_families_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generate/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview
         * @description Generate without saving. Omit `seed` for a fresh one; the returned seed reproduces this exact set.
         */
        post: operations["preview_api_generate_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generate/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save
         * @description Regenerate server-side from the seed (never trusting client-edited content) and store in the bank.
         */
        post: operations["save_api_generate_save_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Questions */
        get: operations["list_questions_api_questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/{question_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Question */
        get: operations["get_question_api_questions__question_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/{question_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Edit Question */
        post: operations["edit_question_api_questions__question_id__versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/{question_id}/restore/{version_no}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore Version
         * @description Make an older version current again by copying it forward as a new version.
         */
        post: operations["restore_version_api_questions__question_id__restore__version_no__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/{question_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Status */
        post: operations["set_status_api_questions__question_id__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/bulk-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk Status */
        post: operations["bulk_status_api_questions_bulk_status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assessments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assessments */
        get: operations["list_assessments_api_assessments_get"];
        put?: never;
        /** Create Assessment */
        post: operations["create_assessment_api_assessments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assessments/{assessment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Assessment */
        get: operations["get_assessment_api_assessments__assessment_id__get"];
        put?: never;
        post?: never;
        /** Delete Assessment */
        delete: operations["delete_assessment_api_assessments__assessment_id__delete"];
        options?: never;
        head?: never;
        /** Update Assessment */
        patch: operations["update_assessment_api_assessments__assessment_id__patch"];
        trace?: never;
    };
    "/api/assessments/{assessment_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Items
         * @description Pin each question's current version. Items sharing a stimulus are kept next to each other.
         */
        post: operations["add_items_api_assessments__assessment_id__items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assessments/{assessment_id}/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Item */
        delete: operations["remove_item_api_assessments__assessment_id__items__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assessments/{assessment_id}/items/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reorder Items */
        put: operations["reorder_items_api_assessments__assessment_id__items_order_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assessments/{assessment_id}/items/{item_id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Item
         * @description Re-pin an item to its question's latest version.
         */
        post: operations["refresh_item_api_assessments__assessment_id__items__item_id__refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assessments/{assessment_id}/print": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Print View
         * @description Printable content. The student variant is built without any key data at all.
         */
        get: operations["print_view_api_assessments__assessment_id__print_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddItems */
        AddItems: {
            /** Question Ids */
            question_ids: number[];
        };
        /** AddItemsOut */
        AddItemsOut: {
            /** Added */
            added: number[];
            /** Skipped */
            skipped: {
                [key: string]: string;
            };
        };
        /** AssessmentCreate */
        AssessmentCreate: {
            /** Title */
            title: string;
            /** Course Id */
            course_id?: number | null;
            /**
             * Instructions
             * @default
             */
            instructions: string;
        };
        /** AssessmentDetail */
        AssessmentDetail: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Course Id */
            course_id: number | null;
            /** Course Name */
            course_name: string | null;
            /** Instructions */
            instructions: string;
            /** Item Count */
            item_count: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Items */
            items: components["schemas"]["AssessmentItemOut"][];
            /** Dok Distribution */
            dok_distribution: {
                [key: string]: number;
            };
            /** Standards Coverage */
            standards_coverage: Record<string, never>[];
            /** Question Type Counts */
            question_type_counts: {
                [key: string]: number;
            };
        };
        /** AssessmentItemOut */
        AssessmentItemOut: {
            /** Id */
            id: number;
            /** Position */
            position: number;
            /** Question Id */
            question_id: number;
            /**
             * Question Status
             * @enum {string}
             */
            question_status: "generated" | "reviewed" | "approved" | "rejected" | "archived";
            /** Pinned Version No */
            pinned_version_no: number;
            /** Latest Version No */
            latest_version_no: number;
            /** Standard Code */
            standard_code: string;
            /** Course Name */
            course_name: string;
            /** Stimulus Id */
            stimulus_id: number | null;
            /** Stimulus Title */
            stimulus_title: string | null;
            /** Dok */
            dok: number;
            /**
             * Question Type
             * @enum {string}
             */
            question_type: "multiple_choice" | "constructed_response";
            /** Stem */
            stem: string;
        };
        /** AssessmentSummary */
        AssessmentSummary: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Course Id */
            course_id: number | null;
            /** Course Name */
            course_name: string | null;
            /** Instructions */
            instructions: string;
            /** Item Count */
            item_count: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** AssessmentUpdate */
        AssessmentUpdate: {
            /** Title */
            title?: string | null;
            /** Course Id */
            course_id?: number | null;
            /** Instructions */
            instructions?: string | null;
        };
        /** BulkStatusChange */
        BulkStatusChange: {
            /**
             * To Status
             * @enum {string}
             */
            to_status: "generated" | "reviewed" | "approved" | "rejected" | "archived";
            /** Note */
            note?: string | null;
            /** Question Ids */
            question_ids: number[];
        };
        /** BulkStatusOut */
        BulkStatusOut: {
            /** Updated */
            updated: number[];
            /** Skipped */
            skipped: {
                [key: string]: string;
            };
        };
        /** BundleOut */
        BundleOut: {
            /** Id */
            id: number;
            /** Course Id */
            course_id: number;
            /** Course Name */
            course_name: string;
            /** Name */
            name: string;
            /** Narrative */
            narrative: string;
            /** Aligned */
            aligned: components["schemas"]["BundleStandardOut"][];
            /** Connected Pes */
            connected_pes: string[];
            /** Example Anchoring Phenomena */
            example_anchoring_phenomena: string[];
            /** Source Document Title */
            source_document_title: string;
        };
        /** BundleRef */
        BundleRef: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Partial */
            partial: boolean;
        };
        /** BundleStandardOut */
        BundleStandardOut: {
            /** Standard Id */
            standard_id: number;
            /** Code */
            code: string;
            /** Partial */
            partial: boolean;
            /** Performance Expectation */
            performance_expectation: string;
        };
        /** ChoiceIn */
        ChoiceIn: {
            /** Text */
            text: string;
            /** Correct */
            correct: boolean;
            /**
             * Rationale
             * @default
             */
            rationale: string;
        };
        /** ChoiceOut */
        ChoiceOut: {
            /** Label */
            label: string;
            /** Text */
            text: string;
            /** Correct */
            correct: boolean;
            /** Rationale */
            rationale: string;
        };
        /** CourseOut */
        CourseOut: {
            /** Id */
            id: number;
            /** State */
            state: string;
            /** Use Year */
            use_year: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Standards Base */
            standards_base: string | null;
            /** Notes */
            notes: string | null;
            /** Active */
            active: boolean;
            /** Standards Count */
            standards_count: number;
            /** Bundles Count */
            bundles_count: number;
            source_document: components["schemas"]["SourceDocumentOut"];
        };
        /** DciOut */
        DciOut: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Text */
            text: string;
        };
        /** FamilyBindingOut */
        FamilyBindingOut: {
            /** State */
            state: string;
            /** Course Slug */
            course_slug: string;
            /** Code */
            code: string;
            /** Standard Ids */
            standard_ids: number[];
        };
        /** FamilyOut */
        FamilyOut: {
            /** Key */
            key: string;
            /** Version */
            version: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Stimulus Kind */
            stimulus_kind: string;
            /** Bindings */
            bindings: components["schemas"]["FamilyBindingOut"][];
            /** Templates */
            templates: components["schemas"]["TemplateOut"][];
        };
        /** FamilyRef */
        FamilyRef: {
            /** Key */
            key: string;
            /** Title */
            title: string;
            /** Version */
            version: string;
        };
        /** GeneratePreviewOut */
        GeneratePreviewOut: {
            /** Family Key */
            family_key: string;
            /** Family Version */
            family_version: string;
            /** Seed */
            seed: string;
            /** Options */
            options: Record<string, never>;
            standard: components["schemas"]["StandardSummary"];
            /** Groups */
            groups: components["schemas"]["GeneratedGroupOut"][];
        };
        /** GenerateRequest */
        GenerateRequest: {
            /** Standard Id */
            standard_id: number;
            /** Family Key */
            family_key: string;
            /** Seed */
            seed?: string | null;
            /**
             * Quantity
             * @default 5
             */
            quantity: number;
            /**
             * Doks
             * @default []
             */
            doks: number[];
            /**
             * Question Types
             * @default []
             */
            question_types: ("multiple_choice" | "constructed_response")[];
            /**
             * Template Keys
             * @default []
             */
            template_keys: string[];
        };
        /** GenerateSaveOut */
        GenerateSaveOut: {
            /** Run Id */
            run_id: number;
            /** Seed */
            seed: string;
            /** Question Ids */
            question_ids: number[];
        };
        /** GeneratedGroupOut */
        GeneratedGroupOut: {
            /** Index */
            index: number;
            /** Parameters */
            parameters: Record<string, never>;
            /** Stimulus */
            stimulus: Record<string, never>;
            /** Questions */
            questions: components["schemas"]["GeneratedQuestionOut"][];
        };
        /** GeneratedQuestionOut */
        GeneratedQuestionOut: {
            /** Template Key */
            template_key: string;
            /** Title */
            title: string;
            /** Dok */
            dok: number;
            /**
             * Question Type
             * @enum {string}
             */
            question_type: "multiple_choice" | "constructed_response";
            /** Stem */
            stem: string;
            /** Choices */
            choices: components["schemas"]["ChoiceOut"][];
            /** Answer */
            answer: string;
            /** Explanation */
            explanation: string;
            observable: components["schemas"]["ObservableRef"];
            /** Attempt */
            attempt: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** NamedText */
        NamedText: {
            /** Name */
            name: string;
            /** Description */
            description: string;
        };
        /** ObservableRef */
        ObservableRef: {
            /** Category */
            category: string;
            /** Index */
            index: number;
            /** Text */
            text?: string | null;
        };
        /** PrintBlock */
        PrintBlock: {
            /** Stimulus */
            stimulus: Record<string, never> | null;
            /** Stimulus Title */
            stimulus_title: string | null;
            /** Questions */
            questions: components["schemas"]["PrintQuestion"][];
        };
        /** PrintChoice */
        PrintChoice: {
            /** Label */
            label: string;
            /** Text */
            text: string;
            /** Correct */
            correct?: boolean | null;
            /** Rationale */
            rationale?: string | null;
        };
        /** PrintOut */
        PrintOut: {
            /**
             * Variant
             * @enum {string}
             */
            variant: "teacher" | "student";
            /** Title */
            title: string;
            /** Course Name */
            course_name: string | null;
            /** Instructions */
            instructions: string;
            /** Question Count */
            question_count: number;
            /** Blocks */
            blocks: components["schemas"]["PrintBlock"][];
            /** Standards */
            standards?: Record<string, never>[] | null;
        };
        /** PrintQuestion */
        PrintQuestion: {
            /** Number */
            number: number;
            /**
             * Question Type
             * @enum {string}
             */
            question_type: "multiple_choice" | "constructed_response";
            /** Dok */
            dok: number;
            /** Standard Code */
            standard_code: string;
            /** Stem */
            stem: string;
            /** Choices */
            choices: components["schemas"]["PrintChoice"][];
            /** Answer */
            answer?: string | null;
            /** Explanation */
            explanation?: string | null;
            /** Teacher Edited */
            teacher_edited?: boolean | null;
        };
        /** QuestionDetail */
        QuestionDetail: {
            /** Id */
            id: number;
            /**
             * Status
             * @enum {string}
             */
            status: "generated" | "reviewed" | "approved" | "rejected" | "archived";
            /** Allowed Transitions */
            allowed_transitions: ("generated" | "reviewed" | "approved" | "rejected" | "archived")[];
            standard: components["schemas"]["StandardSummary"];
            /** Family Key */
            family_key: string | null;
            /** Template Key */
            template_key: string | null;
            /** Provenance */
            provenance: Record<string, never>;
            stimulus: components["schemas"]["StimulusOut"] | null;
            current: components["schemas"]["QuestionVersionOut"];
            /** Versions */
            versions: components["schemas"]["QuestionVersionOut"][];
            /** Status Events */
            status_events: components["schemas"]["StatusEventOut"][];
            /** Assessment Ids */
            assessment_ids: number[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** QuestionEdit */
        QuestionEdit: {
            /** Stem */
            stem: string;
            /** Dok */
            dok: number;
            /**
             * Choices
             * @default []
             */
            choices: components["schemas"]["ChoiceIn"][];
            /** Answer */
            answer?: string | null;
            /**
             * Explanation
             * @default
             */
            explanation: string;
            /** Change Note */
            change_note?: string | null;
        };
        /** QuestionPage */
        QuestionPage: {
            /** Items */
            items: components["schemas"]["QuestionSummary"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Status Counts */
            status_counts: {
                [key: string]: number;
            };
        };
        /** QuestionSummary */
        QuestionSummary: {
            /** Id */
            id: number;
            /**
             * Status
             * @enum {string}
             */
            status: "generated" | "reviewed" | "approved" | "rejected" | "archived";
            /** Standard Id */
            standard_id: number;
            /** Standard Code */
            standard_code: string;
            /** Course Name */
            course_name: string;
            /** Use Year */
            use_year: string;
            /** Family Key */
            family_key: string | null;
            /** Template Key */
            template_key: string | null;
            /** Stimulus Id */
            stimulus_id: number | null;
            /** Stimulus Title */
            stimulus_title: string | null;
            /** Current Version No */
            current_version_no: number;
            /**
             * Origin
             * @enum {string}
             */
            origin: "engine" | "teacher_edit";
            /**
             * Question Type
             * @enum {string}
             */
            question_type: "multiple_choice" | "constructed_response";
            /** Dok */
            dok: number;
            /** Stem */
            stem: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** QuestionVersionOut */
        QuestionVersionOut: {
            /** Id */
            id: number;
            /** Version No */
            version_no: number;
            /**
             * Origin
             * @enum {string}
             */
            origin: "engine" | "teacher_edit";
            /**
             * Question Type
             * @enum {string}
             */
            question_type: "multiple_choice" | "constructed_response";
            /** Dok */
            dok: number;
            /** Stem */
            stem: string;
            /** Choices */
            choices: components["schemas"]["ChoiceOut"][];
            /** Answer */
            answer: string;
            /** Explanation */
            explanation: string;
            /** Change Note */
            change_note: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** RegistrationStatus */
        RegistrationStatus: {
            /** Registration Open */
            registration_open: boolean;
        };
        /** ReorderItems */
        ReorderItems: {
            /** Item Ids */
            item_ids: number[];
        };
        /** SessionUser */
        SessionUser: {
            /** Username */
            username: string;
        };
        /** SourceDocumentOut */
        SourceDocumentOut: {
            /** Id */
            id: number;
            /** State */
            state: string;
            /** Document Key */
            document_key: string;
            /** Title */
            title: string;
            /** Resource Type */
            resource_type: string;
            /** Authority */
            authority: string | null;
            /** Use Year */
            use_year: string | null;
            /** Published */
            published: string | null;
            /** Url */
            url: string | null;
            /** Data File */
            data_file: string | null;
            /** Content Sha256 */
            content_sha256: string | null;
            /**
             * Imported At
             * Format: date-time
             */
            imported_at: string;
        };
        /** StandardDetail */
        StandardDetail: {
            /** Id */
            id: number;
            /** Course Id */
            course_id: number;
            /** Course Name */
            course_name: string;
            /** Course Slug */
            course_slug: string;
            /** Use Year */
            use_year: string;
            /** Code */
            code: string;
            /** Domain Code */
            domain_code: string;
            /** Domain Name */
            domain_name: string;
            /** Performance Expectation */
            performance_expectation: string;
            /** Topics */
            topics: string[];
            /** Question Family Candidate */
            question_family_candidate: boolean;
            /** Repeat Of Biology 1 */
            repeat_of_biology_1: boolean;
            /** Families */
            families: components["schemas"]["FamilyRef"][];
            /** Clarification Statement */
            clarification_statement: string | null;
            /** State Assessment Boundary */
            state_assessment_boundary: string | null;
            sep: components["schemas"]["NamedText"];
            /** Dci */
            dci: components["schemas"]["DciOut"][];
            ccc: components["schemas"]["NamedText"];
            /** Observable Performances */
            observable_performances: {
                [key: string]: string[];
            };
            /** Terminology */
            terminology: string[];
            /** Question Sentence Stems */
            question_sentence_stems: string[] | null;
            /** Content Sha256 */
            content_sha256: string;
            source_document: components["schemas"]["SourceDocumentOut"];
            /** Bundles */
            bundles: components["schemas"]["BundleRef"][];
            /** Question Counts */
            question_counts: {
                [key: string]: number;
            };
        };
        /** StandardSummary */
        StandardSummary: {
            /** Id */
            id: number;
            /** Course Id */
            course_id: number;
            /** Course Name */
            course_name: string;
            /** Course Slug */
            course_slug: string;
            /** Use Year */
            use_year: string;
            /** Code */
            code: string;
            /** Domain Code */
            domain_code: string;
            /** Domain Name */
            domain_name: string;
            /** Performance Expectation */
            performance_expectation: string;
            /** Topics */
            topics: string[];
            /** Question Family Candidate */
            question_family_candidate: boolean;
            /** Repeat Of Biology 1 */
            repeat_of_biology_1: boolean;
            /** Families */
            families: components["schemas"]["FamilyRef"][];
        };
        /** StatusChange */
        StatusChange: {
            /**
             * To Status
             * @enum {string}
             */
            to_status: "generated" | "reviewed" | "approved" | "rejected" | "archived";
            /** Note */
            note?: string | null;
        };
        /** StatusEventOut */
        StatusEventOut: {
            /** Id */
            id: number;
            /** From Status */
            from_status: string | null;
            /** To Status */
            to_status: string;
            /** Note */
            note: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** StimulusOut */
        StimulusOut: {
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Title */
            title: string;
            /** Body */
            body: Record<string, never>;
        };
        /** TemplateOut */
        TemplateOut: {
            /** Key */
            key: string;
            /** Title */
            title: string;
            /** Dok */
            dok: number;
            /**
             * Question Type
             * @enum {string}
             */
            question_type: "multiple_choice" | "constructed_response";
            /** Observable Category */
            observable_category: string;
            /** Observable Index */
            observable_index: number;
            /** Observable Text */
            observable_text?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionUser"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    registration_status_api_auth_registration_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationStatus"];
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionUser"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                science_bank_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionUser"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_courses_api_courses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                science_bank_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_standards_api_standards_get: {
        parameters: {
            query?: {
                course_id?: number | null;
                q?: string | null;
                domain?: string | null;
                topic?: string | null;
                candidate_only?: boolean;
                with_family_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                science_bank_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandardSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_standard_detail_api_standards__standard_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                standard_id: number;
            };
            cookie?: {
                science_bank_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandardDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_topics_api_topics_get: {
        parameters: {
            query?: {
                course_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                science_bank_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bundles_api_bundles_get: {
        parameters: {
            query?: {
                course_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                science_bank_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BundleOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_api_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                science_bank_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDocumentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_families_api_families_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                science_bank_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_api_generate_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                science_bank_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratePreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_api_generate_save_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                science_bank_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateSaveOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_questions_api_questions_get: {
        parameters: {
            query?: {
                status?: ("generated" | "reviewed" | "approved" | "rejected" | "archived")[];
                course_id?: number | null;
                standard_id?: number | null;
                family_key?: string | null;
                dok?: number[];
                question_type?: ("multiple_choice" | "constructed_response") | null;
                stimulus_id?: number | null;
                q?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                science_bank_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_question_api_questions__question_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: number;
            };
            cookie?: {
                science_bank_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_question_api_questions__question_id__versions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: number;
            };
            cookie?: {
                science_bank_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_version_api_questions__question_id__restore__version_no__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: number;
                version_no: number;
            };
            cookie?: {
                science_bank_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_status_api_questions__question_id__status_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: number;
            };
            cookie?: {
                science_bank_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_status_api_questions_bulk_status_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                science_bank_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkStatusChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assessments_api_assessments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                science_bank_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_assessment_api_assessments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                science_bank_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssessmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_assessment_api_assessments__assessment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: number;
            };
            cookie?: {
                science_bank_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_assessment_api_assessments__assessment_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: number;
            };
            cookie?: {
                science_bank_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_assessment_api_assessments__assessment_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: number;
            };
            cookie?: {
                science_bank_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssessmentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_items_api_assessments__assessment_id__items_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: number;
            };
            cookie?: {
                science_bank_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddItems"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddItemsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_item_api_assessments__assessment_id__items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: number;
                item_id: number;
            };
            cookie?: {
                science_bank_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_items_api_assessments__assessment_id__items_order_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: number;
            };
            cookie?: {
                science_bank_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderItems"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_item_api_assessments__assessment_id__items__item_id__refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assessment_id: number;
                item_id: number;
            };
            cookie?: {
                science_bank_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    print_view_api_assessments__assessment_id__print_get: {
        parameters: {
            query?: {
                variant?: "teacher" | "student";
            };
            header?: never;
            path: {
                assessment_id: number;
            };
            cookie?: {
                science_bank_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrintOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
